### ISSUE TITLE
Trying to implement in my code, but something don't work...

### ISSUE THREAD

**Issue by jordiSabartresCastillo** [yyx990803/laravel-vue-cli-3#24]
Im trying to link my vue.cli project to laravel and I follow the steps but I have this error, and I don't know how i can solve. 

InvalidArgumentException
View [index] not found.

    protected function findInPaths($name, $paths)
    {
        foreach ((array) $paths as $path) {
            foreach ($this->getPossibleViewFiles($name) as $file) {
                if ($this->files->exists($viewPath = $path.'/'.$file)) {
                    return $viewPath;
                }
            }
        }
 
       ------ red line ----- throw new InvalidArgumentException("View [{$name}] not found.");
    }
 
    /**
     * Get an array of possible view files.
     *
     * @param  string  $name
     * @return array
     */
    protected function getPossibleViewFiles($name)
    {
        return array_map(function ($extension) use ($name) {
            return str_replace('.', '/', $name).'.'.$extension;
        }, $this->extensions);
    }

**Comment by louisdesmet** [comment]
because laravel has the basic view welcome and not index, just change the name to index
